<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Phase-2 expansion of hcm_salary_components master data.
 *
 * New components in this migration:
 *
 * ADDITIONS
 *   Fixed allowances      : tunjangan_keluarga, tunjangan_perumahan, tunjangan_kesehatan_tetap
 *   Irregular allowances  : uang_makan_harian, uang_transport_harian
 *   Bonus / incentive     : insentif_kinerja, insentif_target_penjualan, uang_cuti
 *   Special               : tunjangan_relokasi, uang_duka
 *   Reimbursement         : reimbursement_kesehatan, reimbursement_pendidikan,
 *                           reimbursement_transportasi, reimbursement_lain
 *   Termination benefits  : uang_pesangon, uang_penghargaan_masa_kerja, uang_pisah
 *   Employer cost display : iuran_dplk_pk
 *
 * DEDUCTIONS
 *   Statutory / pension   : iuran_dplk_pekerja
 *   Absence / leave       : potongan_cuti_diluar_tanggungan
 *   Internal              : potongan_kasbon, potongan_overpayment, potongan_seragam
 */
return new class extends Migration
{
    public function up(): void
    {
        $now = now();

        $rows = [

            // ─────────────────────────────────────────────────────────────────
            // ADDITIONS — Fixed Allowances (sort 32–38)
            // ─────────────────────────────────────────────────────────────────
            [
                'code'                             => 'tunjangan_keluarga',
                'name'                             => 'Tunjangan Keluarga / Anak',
                'description'                      => 'Tunjangan tetap berdasarkan status pernikahan dan jumlah tanggungan.',
                'kind'                             => 'addition',
                'category'                         => 'fixed_allowance',
                'legal_basis'                      => 'Perjanjian kerja / PKB / kebijakan perusahaan.',
                'legal_notes'                      => 'Jika bersifat tetap masuk basis THR dan BPJS sesuai kebijakan.',
                'include_bpjs_health_wage_base'    => true,
                'include_bpjs_tk_wage_base'        => true,
                'include_thr_calculation_base'     => true,
                'include_pph21_ter_gross'          => true,
                'include_pph21_annual_reconciliation' => true,
                'subject_overtime_regulation'      => false,
                'affects_net_pay'                  => true,
                'employer_cost_line'               => false,
                'is_system_locked'                 => false,
                'sort_order'                       => 32,
                'is_active'                        => true,
            ],
            [
                'code'                             => 'tunjangan_perumahan',
                'name'                             => 'Tunjangan Tetap — Perumahan',
                'description'                      => 'Tunjangan perumahan yang dibayarkan tetap setiap bulan.',
                'kind'                             => 'addition',
                'category'                         => 'fixed_allowance',
                'legal_basis'                      => 'Perjanjian kerja / PKB / kebijakan perusahaan.',
                'legal_notes'                      => 'Diklasifikasikan sebagai tunjangan tetap untuk keperluan THR dan pajak.',
                'include_bpjs_health_wage_base'    => true,
                'include_bpjs_tk_wage_base'        => true,
                'include_thr_calculation_base'     => true,
                'include_pph21_ter_gross'          => true,
                'include_pph21_annual_reconciliation' => true,
                'subject_overtime_regulation'      => false,
                'affects_net_pay'                  => true,
                'employer_cost_line'               => false,
                'is_system_locked'                 => false,
                'sort_order'                       => 35,
                'is_active'                        => true,
            ],
            [
                'code'                             => 'tunjangan_kesehatan_tetap',
                'name'                             => 'Tunjangan Kesehatan Tetap',
                'description'                      => 'Tunjangan kesehatan bersifat tetap di luar BPJS Kesehatan.',
                'kind'                             => 'addition',
                'category'                         => 'fixed_allowance',
                'legal_basis'                      => 'Perjanjian kerja / PKB.',
                'legal_notes'                      => 'Tidak menggantikan kewajiban BPJS Kesehatan. Masuk basis THR jika tetap.',
                'include_bpjs_health_wage_base'    => true,
                'include_bpjs_tk_wage_base'        => true,
                'include_thr_calculation_base'     => true,
                'include_pph21_ter_gross'          => true,
                'include_pph21_annual_reconciliation' => true,
                'subject_overtime_regulation'      => false,
                'affects_net_pay'                  => true,
                'employer_cost_line'               => false,
                'is_system_locked'                 => false,
                'sort_order'                       => 37,
                'is_active'                        => true,
            ],

            // ─────────────────────────────────────────────────────────────────
            // ADDITIONS — Irregular Allowances (sort 51–54)
            // ─────────────────────────────────────────────────────────────────
            [
                'code'                             => 'uang_makan_harian',
                'name'                             => 'Uang Makan Harian (tidak tetap)',
                'description'                      => 'Uang makan dihitung per hari hadir; tidak bersifat tetap.',
                'kind'                             => 'addition',
                'category'                         => 'irregular_allowance',
                'legal_basis'                      => 'Kebijakan perusahaan.',
                'legal_notes'                      => 'Tidak masuk basis THR dan BPJS karena dibayar berdasarkan kehadiran.',
                'include_bpjs_health_wage_base'    => false,
                'include_bpjs_tk_wage_base'        => false,
                'include_thr_calculation_base'     => false,
                'include_pph21_ter_gross'          => true,
                'include_pph21_annual_reconciliation' => true,
                'subject_overtime_regulation'      => false,
                'affects_net_pay'                  => true,
                'employer_cost_line'               => false,
                'is_system_locked'                 => false,
                'sort_order'                       => 51,
                'is_active'                        => true,
            ],
            [
                'code'                             => 'uang_transport_harian',
                'name'                             => 'Uang Transport Harian (tidak tetap)',
                'description'                      => 'Uang transport dihitung per hari hadir; tidak bersifat tetap.',
                'kind'                             => 'addition',
                'category'                         => 'irregular_allowance',
                'legal_basis'                      => 'Kebijakan perusahaan.',
                'legal_notes'                      => 'Tidak masuk basis THR dan BPJS karena dibayar berdasarkan kehadiran.',
                'include_bpjs_health_wage_base'    => false,
                'include_bpjs_tk_wage_base'        => false,
                'include_thr_calculation_base'     => false,
                'include_pph21_ter_gross'          => true,
                'include_pph21_annual_reconciliation' => true,
                'subject_overtime_regulation'      => false,
                'affects_net_pay'                  => true,
                'employer_cost_line'               => false,
                'is_system_locked'                 => false,
                'sort_order'                       => 52,
                'is_active'                        => true,
            ],

            // ─────────────────────────────────────────────────────────────────
            // ADDITIONS — Bonus / Incentive (sort 86–90)
            // ─────────────────────────────────────────────────────────────────
            [
                'code'                             => 'insentif_kinerja',
                'name'                             => 'Insentif Kinerja (KPI)',
                'description'                      => 'Insentif berdasarkan pencapaian KPI individu atau tim.',
                'kind'                             => 'addition',
                'category'                         => 'bonus',
                'legal_basis'                      => 'Sistem kompensasi berbasis kinerja sesuai perjanjian kerja / KPI policy.',
                'legal_notes'                      => 'Tidak masuk basis THR dan BPJS; masuk gross PPh 21.',
                'include_bpjs_health_wage_base'    => false,
                'include_bpjs_tk_wage_base'        => false,
                'include_thr_calculation_base'     => false,
                'include_pph21_ter_gross'          => true,
                'include_pph21_annual_reconciliation' => true,
                'subject_overtime_regulation'      => false,
                'affects_net_pay'                  => true,
                'employer_cost_line'               => false,
                'is_system_locked'                 => false,
                'sort_order'                       => 86,
                'is_active'                        => true,
            ],
            [
                'code'                             => 'insentif_target_penjualan',
                'name'                             => 'Insentif Target Penjualan',
                'description'                      => 'Insentif atas pencapaian target penjualan tertentu (di luar komisi reguler).',
                'kind'                             => 'addition',
                'category'                         => 'bonus',
                'legal_basis'                      => 'Kebijakan sales incentive / perjanjian kerja.',
                'legal_notes'                      => null,
                'include_bpjs_health_wage_base'    => false,
                'include_bpjs_tk_wage_base'        => false,
                'include_thr_calculation_base'     => false,
                'include_pph21_ter_gross'          => true,
                'include_pph21_annual_reconciliation' => true,
                'subject_overtime_regulation'      => false,
                'affects_net_pay'                  => true,
                'employer_cost_line'               => false,
                'is_system_locked'                 => false,
                'sort_order'                       => 87,
                'is_active'                        => true,
            ],
            [
                'code'                             => 'uang_cuti',
                'name'                             => 'Uang Cuti / Buyback Cuti',
                'description'                      => 'Pembayaran penggantian sisa cuti yang tidak diambil (cuti buyback / carry-over).',
                'kind'                             => 'addition',
                'category'                         => 'bonus',
                'legal_basis'                      => 'Perjanjian kerja / PKB tentang penggantian cuti.',
                'legal_notes'                      => 'Perlakuan pajak mengikuti PPh 21 — umumnya masuk gross penghasilan. Konsultasikan dengan konsultan pajak untuk pembayaran sekaligus.',
                'include_bpjs_health_wage_base'    => false,
                'include_bpjs_tk_wage_base'        => false,
                'include_thr_calculation_base'     => false,
                'include_pph21_ter_gross'          => true,
                'include_pph21_annual_reconciliation' => true,
                'subject_overtime_regulation'      => false,
                'affects_net_pay'                  => true,
                'employer_cost_line'               => false,
                'is_system_locked'                 => false,
                'sort_order'                       => 88,
                'is_active'                        => true,
            ],

            // ─────────────────────────────────────────────────────────────────
            // ADDITIONS — Special / Non-recurring (sort 93–95)
            // ─────────────────────────────────────────────────────────────────
            [
                'code'                             => 'tunjangan_relokasi',
                'name'                             => 'Tunjangan Relokasi',
                'description'                      => 'Kompensasi biaya pindah / relokasi karyawan; bersifat insidentil.',
                'kind'                             => 'addition',
                'category'                         => 'special_allowance',
                'legal_basis'                      => 'Perjanjian kerja / kebijakan relokasi perusahaan.',
                'legal_notes'                      => 'Masuk gross PPh 21 jika tidak dapat dikualifikasikan sebagai penggantian biaya nyata.',
                'include_bpjs_health_wage_base'    => false,
                'include_bpjs_tk_wage_base'        => false,
                'include_thr_calculation_base'     => false,
                'include_pph21_ter_gross'          => true,
                'include_pph21_annual_reconciliation' => true,
                'subject_overtime_regulation'      => false,
                'affects_net_pay'                  => true,
                'employer_cost_line'               => false,
                'is_system_locked'                 => false,
                'sort_order'                       => 93,
                'is_active'                        => true,
            ],
            [
                'code'                             => 'uang_duka',
                'name'                             => 'Uang Duka / Santunan Keluarga',
                'description'                      => 'Santunan yang diberikan atas kedukaan (kematian keluarga inti).',
                'kind'                             => 'addition',
                'category'                         => 'special_allowance',
                'legal_basis'                      => 'Kebijakan perusahaan / PKB.',
                'legal_notes'                      => 'Umumnya diberikan satu kali; perlakuan pajak tergantung kebijakan dan jumlah.',
                'include_bpjs_health_wage_base'    => false,
                'include_bpjs_tk_wage_base'        => false,
                'include_thr_calculation_base'     => false,
                'include_pph21_ter_gross'          => true,
                'include_pph21_annual_reconciliation' => true,
                'subject_overtime_regulation'      => false,
                'affects_net_pay'                  => true,
                'employer_cost_line'               => false,
                'is_system_locked'                 => false,
                'sort_order'                       => 94,
                'is_active'                        => true,
            ],
            [
                'code'                             => 'tunjangan_pernikahan',
                'name'                             => 'Tunjangan / Hadiah Pernikahan Karyawan',
                'description'                      => 'Diberikan sekali saat karyawan menikah.',
                'kind'                             => 'addition',
                'category'                         => 'special_allowance',
                'legal_basis'                      => 'Kebijakan perusahaan / PKB.',
                'legal_notes'                      => 'Masuk penghasilan PPh 21 jika dalam bentuk uang tunai.',
                'include_bpjs_health_wage_base'    => false,
                'include_bpjs_tk_wage_base'        => false,
                'include_thr_calculation_base'     => false,
                'include_pph21_ter_gross'          => true,
                'include_pph21_annual_reconciliation' => true,
                'subject_overtime_regulation'      => false,
                'affects_net_pay'                  => true,
                'employer_cost_line'               => false,
                'is_system_locked'                 => false,
                'sort_order'                       => 95,
                'is_active'                        => true,
            ],

            // ─────────────────────────────────────────────────────────────────
            // ADDITIONS — Reimbursement (sort 120–125)
            // ─────────────────────────────────────────────────────────────────
            [
                'code'                             => 'reimbursement_kesehatan',
                'name'                             => 'Reimbursement Kesehatan',
                'description'                      => 'Penggantian biaya kesehatan berdasarkan bukti/kwitansi yang sah.',
                'kind'                             => 'addition',
                'category'                         => 'reimbursement',
                'legal_basis'                      => 'PMK No. 66/PMK.03/2023 tentang perlakuan pajak atas penggantian biaya.',
                'legal_notes'                      => 'Reimbursement "murni" (at-cost, didukung bukti) dapat dikecualikan dari objek PPh 21 — konfirmasi dengan tax consultant. Jika dibayar flat setiap bulan, perlakukan sebagai tunjangan.',
                'include_bpjs_health_wage_base'    => false,
                'include_bpjs_tk_wage_base'        => false,
                'include_thr_calculation_base'     => false,
                'include_pph21_ter_gross'          => false,
                'include_pph21_annual_reconciliation' => false,
                'subject_overtime_regulation'      => false,
                'affects_net_pay'                  => true,
                'employer_cost_line'               => false,
                'is_system_locked'                 => false,
                'sort_order'                       => 120,
                'is_active'                        => true,
            ],
            [
                'code'                             => 'reimbursement_pendidikan',
                'name'                             => 'Reimbursement Pendidikan / Pelatihan',
                'description'                      => 'Penggantian biaya pendidikan, sertifikasi, atau pelatihan karyawan.',
                'kind'                             => 'addition',
                'category'                         => 'reimbursement',
                'legal_basis'                      => 'PKB / kebijakan pengembangan SDM perusahaan.',
                'legal_notes'                      => 'Biaya pelatihan yang dikeluarkan untuk kepentingan perusahaan umumnya bukan objek PPh Pasal 21 pekerja — dokumentasi wajib lengkap.',
                'include_bpjs_health_wage_base'    => false,
                'include_bpjs_tk_wage_base'        => false,
                'include_thr_calculation_base'     => false,
                'include_pph21_ter_gross'          => false,
                'include_pph21_annual_reconciliation' => false,
                'subject_overtime_regulation'      => false,
                'affects_net_pay'                  => true,
                'employer_cost_line'               => false,
                'is_system_locked'                 => false,
                'sort_order'                       => 121,
                'is_active'                        => true,
            ],
            [
                'code'                             => 'reimbursement_transportasi',
                'name'                             => 'Reimbursement Transportasi / Perjalanan Dinas',
                'description'                      => 'Penggantian biaya transportasi dan perjalanan dinas berdasarkan bukti nyata.',
                'kind'                             => 'addition',
                'category'                         => 'reimbursement',
                'legal_basis'                      => 'Surat Edaran / PKB terkait uang perjalanan dinas.',
                'legal_notes'                      => 'Perjalanan dinas at-cost pada umumnya tidak dipotong PPh 21. Jika diberi lump-sum di luar biaya nyata, selisihnya dapat menjadi objek pajak.',
                'include_bpjs_health_wage_base'    => false,
                'include_bpjs_tk_wage_base'        => false,
                'include_thr_calculation_base'     => false,
                'include_pph21_ter_gross'          => false,
                'include_pph21_annual_reconciliation' => false,
                'subject_overtime_regulation'      => false,
                'affects_net_pay'                  => true,
                'employer_cost_line'               => false,
                'is_system_locked'                 => false,
                'sort_order'                       => 122,
                'is_active'                        => true,
            ],
            [
                'code'                             => 'reimbursement_pulsa',
                'name'                             => 'Reimbursement Pulsa / Internet',
                'description'                      => 'Penggantian biaya pulsa atau paket internet untuk keperluan kerja.',
                'kind'                             => 'addition',
                'category'                         => 'reimbursement',
                'legal_basis'                      => 'Kebijakan perusahaan.',
                'legal_notes'                      => 'Jika berdasarkan bukti actual cost, umumnya dikecualikan dari PPh 21. Flat allowance masuk sebagai tunjangan komunikasi.',
                'include_bpjs_health_wage_base'    => false,
                'include_bpjs_tk_wage_base'        => false,
                'include_thr_calculation_base'     => false,
                'include_pph21_ter_gross'          => false,
                'include_pph21_annual_reconciliation' => false,
                'subject_overtime_regulation'      => false,
                'affects_net_pay'                  => true,
                'employer_cost_line'               => false,
                'is_system_locked'                 => false,
                'sort_order'                       => 123,
                'is_active'                        => true,
            ],
            [
                'code'                             => 'reimbursement_lain',
                'name'                             => 'Reimbursement Lainnya',
                'description'                      => 'Penggantian biaya lain yang tidak masuk kategori di atas.',
                'kind'                             => 'addition',
                'category'                         => 'reimbursement',
                'legal_basis'                      => 'Kebijakan perusahaan.',
                'legal_notes'                      => 'Perlakuan pajak tergantung jenis biaya dan dokumentasi — review dengan tax consultant.',
                'include_bpjs_health_wage_base'    => false,
                'include_bpjs_tk_wage_base'        => false,
                'include_thr_calculation_base'     => false,
                'include_pph21_ter_gross'          => true,
                'include_pph21_annual_reconciliation' => true,
                'subject_overtime_regulation'      => false,
                'affects_net_pay'                  => true,
                'employer_cost_line'               => false,
                'is_system_locked'                 => false,
                'sort_order'                       => 124,
                'is_active'                        => true,
            ],

            // ─────────────────────────────────────────────────────────────────
            // ADDITIONS — Termination Benefits (sort 130–133)
            // ─────────────────────────────────────────────────────────────────
            [
                'code'                             => 'uang_pesangon',
                'name'                             => 'Uang Pesangon',
                'description'                      => 'Uang pesangon atas PHK sesuai ketentuan UU Ketenagakerjaan.',
                'kind'                             => 'addition',
                'category'                         => 'termination_benefit',
                'legal_basis'                      => 'UU No. 13 Tahun 2003 jo. UU Cipta Kerja (UU No. 11 Tahun 2020) — pasal pesangon; PP No. 35 Tahun 2021.',
                'legal_notes'                      => 'Dikenakan PPh Pasal 21 Final atas pesangon (PP No. 68 Tahun 2009). Tidak masuk payroll bulanan reguler; gunakan run terpisah jika perlu.',
                'include_bpjs_health_wage_base'    => false,
                'include_bpjs_tk_wage_base'        => false,
                'include_thr_calculation_base'     => false,
                'include_pph21_ter_gross'          => false,
                'include_pph21_annual_reconciliation' => false,
                'subject_overtime_regulation'      => false,
                'affects_net_pay'                  => true,
                'employer_cost_line'               => false,
                'is_system_locked'                 => false,
                'sort_order'                       => 130,
                'is_active'                        => true,
            ],
            [
                'code'                             => 'uang_penghargaan_masa_kerja',
                'name'                             => 'Uang Penghargaan Masa Kerja (UPMK)',
                'description'                      => 'Uang penghargaan masa kerja atas PHK / pensiun sesuai UU.',
                'kind'                             => 'addition',
                'category'                         => 'termination_benefit',
                'legal_basis'                      => 'UU No. 13 Tahun 2003 jo. UU Cipta Kerja; PP No. 35 Tahun 2021.',
                'legal_notes'                      => 'Dikenakan PPh 21 Final bersama pesangon (PP 68/2009). Hitung terpisah dari pesangon.',
                'include_bpjs_health_wage_base'    => false,
                'include_bpjs_tk_wage_base'        => false,
                'include_thr_calculation_base'     => false,
                'include_pph21_ter_gross'          => false,
                'include_pph21_annual_reconciliation' => false,
                'subject_overtime_regulation'      => false,
                'affects_net_pay'                  => true,
                'employer_cost_line'               => false,
                'is_system_locked'                 => false,
                'sort_order'                       => 131,
                'is_active'                        => true,
            ],
            [
                'code'                             => 'uang_pisah',
                'name'                             => 'Uang Pisah',
                'description'                      => 'Uang pisah bagi karyawan yang mengundurkan diri atau kondisi tertentu.',
                'kind'                             => 'addition',
                'category'                         => 'termination_benefit',
                'legal_basis'                      => 'UU No. 13 Tahun 2003 jo. UU Cipta Kerja; PP No. 35 Tahun 2021 (Pasal uang pisah).',
                'legal_notes'                      => 'Tidak termasuk pesangon; perlakuan pajak mengikuti ketentuan PPh 21.',
                'include_bpjs_health_wage_base'    => false,
                'include_bpjs_tk_wage_base'        => false,
                'include_thr_calculation_base'     => false,
                'include_pph21_ter_gross'          => true,
                'include_pph21_annual_reconciliation' => true,
                'subject_overtime_regulation'      => false,
                'affects_net_pay'                  => true,
                'employer_cost_line'               => false,
                'is_system_locked'                 => false,
                'sort_order'                       => 132,
                'is_active'                        => true,
            ],
            [
                'code'                             => 'uang_penggantian_hak',
                'name'                             => 'Uang Penggantian Hak (UPH)',
                'description'                      => 'Penggantian hak atas cuti yang belum diambil, biaya perumahan/kesehatan, dll. saat PHK.',
                'kind'                             => 'addition',
                'category'                         => 'termination_benefit',
                'legal_basis'                      => 'PP No. 35 Tahun 2021 Pasal 40 — Uang Penggantian Hak.',
                'legal_notes'                      => 'Komponen UPH berbeda-beda; dokumentasikan rincian per komponen saat dibayarkan.',
                'include_bpjs_health_wage_base'    => false,
                'include_bpjs_tk_wage_base'        => false,
                'include_thr_calculation_base'     => false,
                'include_pph21_ter_gross'          => false,
                'include_pph21_annual_reconciliation' => false,
                'subject_overtime_regulation'      => false,
                'affects_net_pay'                  => true,
                'employer_cost_line'               => false,
                'is_system_locked'                 => false,
                'sort_order'                       => 133,
                'is_active'                        => true,
            ],

            // ─────────────────────────────────────────────────────────────────
            // ADDITIONS — Employer Cost Display (sort 250)
            // ─────────────────────────────────────────────────────────────────
            [
                'code'                             => 'iuran_dplk_pk',
                'name'                             => 'Iuran DPLK / Dana Pensiun (beban perusahaan — informasi slip)',
                'description'                      => 'Kontribusi perusahaan ke Dana Pensiun Lembaga Keuangan (DPLK); informatif di slip.',
                'kind'                             => 'addition',
                'category'                         => 'employer_cost_display',
                'legal_basis'                      => 'UU No. 11 Tahun 1992 tentang Dana Pensiun; kebijakan benefit perusahaan.',
                'legal_notes'                      => 'Tidak mengurangi THP pekerja. Tarif iuran mengikuti ketentuan perjanjian DPLK.',
                'include_bpjs_health_wage_base'    => false,
                'include_bpjs_tk_wage_base'        => false,
                'include_thr_calculation_base'     => false,
                'include_pph21_ter_gross'          => false,
                'include_pph21_annual_reconciliation' => false,
                'subject_overtime_regulation'      => false,
                'affects_net_pay'                  => false,
                'employer_cost_line'               => true,
                'is_system_locked'                 => false,
                'sort_order'                       => 250,
                'is_active'                        => true,
            ],

            // ─────────────────────────────────────────────────────────────────
            // DEDUCTIONS — Pension / DPLK Employee (sort 325)
            // ─────────────────────────────────────────────────────────────────
            [
                'code'                             => 'iuran_dplk_pekerja',
                'name'                             => 'Iuran DPLK / Dana Pensiun (pekerja)',
                'description'                      => 'Potongan iuran Dana Pensiun Lembaga Keuangan bagian pekerja.',
                'kind'                             => 'deduction',
                'category'                         => 'pension_employee',
                'legal_basis'                      => 'UU No. 11 Tahun 1992 tentang Dana Pensiun; perjanjian program pensiun.',
                'legal_notes'                      => 'Iuran DPLK pekerja dapat dikurangkan dari penghasilan bruto hingga batas yang diatur PMK.',
                'include_bpjs_health_wage_base'    => false,
                'include_bpjs_tk_wage_base'        => false,
                'include_thr_calculation_base'     => false,
                'include_pph21_ter_gross'          => false,
                'include_pph21_annual_reconciliation' => false,
                'subject_overtime_regulation'      => false,
                'affects_net_pay'                  => true,
                'employer_cost_line'               => false,
                'is_system_locked'                 => false,
                'sort_order'                       => 325,
                'is_active'                        => true,
            ],

            // ─────────────────────────────────────────────────────────────────
            // DEDUCTIONS — Absence / Leave (sort 352–358)
            // ─────────────────────────────────────────────────────────────────
            [
                'code'                             => 'potongan_cuti_diluar_tanggungan',
                'name'                             => 'Potongan Cuti di Luar Tanggungan (CDLT)',
                'description'                      => 'Potongan gaji selama cuti di luar tanggungan perusahaan.',
                'kind'                             => 'deduction',
                'category'                         => 'other_deduction',
                'legal_basis'                      => 'UU Ketenagakerjaan & kebijakan cuti perusahaan.',
                'legal_notes'                      => 'Dimungkinkan untuk pegawai BUMN/swasta sesuai perjanjian kerja.',
                'include_bpjs_health_wage_base'    => false,
                'include_bpjs_tk_wage_base'        => false,
                'include_thr_calculation_base'     => false,
                'include_pph21_ter_gross'          => false,
                'include_pph21_annual_reconciliation' => false,
                'subject_overtime_regulation'      => false,
                'affects_net_pay'                  => true,
                'employer_cost_line'               => false,
                'is_system_locked'                 => false,
                'sort_order'                       => 352,
                'is_active'                        => true,
            ],

            // ─────────────────────────────────────────────────────────────────
            // DEDUCTIONS — Internal Advance / Overpayment (sort 412–417)
            // ─────────────────────────────────────────────────────────────────
            [
                'code'                             => 'potongan_kasbon',
                'name'                             => 'Potongan Kasbon / Uang Muka Kerja',
                'description'                      => 'Cicilan pengembalian uang muka / kasbon yang diberikan perusahaan.',
                'kind'                             => 'deduction',
                'category'                         => 'internal_advance',
                'legal_basis'                      => 'Perjanjian kasbon / SOP internal perusahaan.',
                'legal_notes'                      => 'Bukan kewajiban perpajakan. Dokumentasikan nominal kasbon dan jadwal cicilan.',
                'include_bpjs_health_wage_base'    => false,
                'include_bpjs_tk_wage_base'        => false,
                'include_thr_calculation_base'     => false,
                'include_pph21_ter_gross'          => false,
                'include_pph21_annual_reconciliation' => false,
                'subject_overtime_regulation'      => false,
                'affects_net_pay'                  => true,
                'employer_cost_line'               => false,
                'is_system_locked'                 => false,
                'sort_order'                       => 412,
                'is_active'                        => true,
            ],
            [
                'code'                             => 'potongan_overpayment',
                'name'                             => 'Pengembalian Kelebihan Pembayaran (Overpayment)',
                'description'                      => 'Pemulihan kelebihan gaji yang terjadi pada periode sebelumnya.',
                'kind'                             => 'deduction',
                'category'                         => 'other_deduction',
                'legal_basis'                      => 'Perjanjian kerja / kebijakan koreksi penggajian.',
                'legal_notes'                      => 'Wajib ada persetujuan tertulis dari pekerja sebelum dilakukan potongan.',
                'include_bpjs_health_wage_base'    => false,
                'include_bpjs_tk_wage_base'        => false,
                'include_thr_calculation_base'     => false,
                'include_pph21_ter_gross'          => false,
                'include_pph21_annual_reconciliation' => false,
                'subject_overtime_regulation'      => false,
                'affects_net_pay'                  => true,
                'employer_cost_line'               => false,
                'is_system_locked'                 => false,
                'sort_order'                       => 416,
                'is_active'                        => true,
            ],
            [
                'code'                             => 'potongan_seragam',
                'name'                             => 'Potongan Seragam / Alat Kerja',
                'description'                      => 'Cicilan biaya seragam, alat kerja, atau perlengkapan yang dipinjamkan.',
                'kind'                             => 'deduction',
                'category'                         => 'internal_other',
                'legal_basis'                      => 'Peraturan perusahaan / perjanjian kerja.',
                'legal_notes'                      => 'Sesuaikan dengan ketentuan Pasal 93 UU Ketenagakerjaan tentang upah tidak dibayar.',
                'include_bpjs_health_wage_base'    => false,
                'include_bpjs_tk_wage_base'        => false,
                'include_thr_calculation_base'     => false,
                'include_pph21_ter_gross'          => false,
                'include_pph21_annual_reconciliation' => false,
                'subject_overtime_regulation'      => false,
                'affects_net_pay'                  => true,
                'employer_cost_line'               => false,
                'is_system_locked'                 => false,
                'sort_order'                       => 435,
                'is_active'                        => true,
            ],
        ];

        foreach ($rows as $row) {
            $exists = DB::table('hcm_salary_components')->where('code', $row['code'])->exists();
            if ($exists) {
                DB::table('hcm_salary_components')
                    ->where('code', $row['code'])
                    ->update(array_merge($row, ['updated_at' => $now]));
                continue;
            }

            DB::table('hcm_salary_components')->insert(array_merge($row, [
                'created_at' => $now,
                'updated_at' => $now,
            ]));
        }
    }

    public function down(): void
    {
        DB::table('hcm_salary_components')->whereIn('code', [
            // Fixed allowances
            'tunjangan_keluarga',
            'tunjangan_perumahan',
            'tunjangan_kesehatan_tetap',
            // Irregular allowances
            'uang_makan_harian',
            'uang_transport_harian',
            // Bonus / incentive
            'insentif_kinerja',
            'insentif_target_penjualan',
            'uang_cuti',
            // Special
            'tunjangan_relokasi',
            'uang_duka',
            'tunjangan_pernikahan',
            // Reimbursement
            'reimbursement_kesehatan',
            'reimbursement_pendidikan',
            'reimbursement_transportasi',
            'reimbursement_pulsa',
            'reimbursement_lain',
            // Termination
            'uang_pesangon',
            'uang_penghargaan_masa_kerja',
            'uang_pisah',
            'uang_penggantian_hak',
            // Employer cost
            'iuran_dplk_pk',
            // Deductions
            'iuran_dplk_pekerja',
            'potongan_cuti_diluar_tanggungan',
            'potongan_kasbon',
            'potongan_overpayment',
            'potongan_seragam',
        ])->delete();
    }
};
