<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('hcm_salary_components', function (Blueprint $table) {
            $table->id();
            $table->string('code', 64)->unique();
            $table->string('name', 200);
            $table->text('description')->nullable();
            $table->string('kind', 32); // addition | deduction
            $table->string('category', 64);
            $table->string('legal_basis', 500)->nullable();
            $table->text('legal_notes')->nullable();
            $table->boolean('include_bpjs_health_wage_base')->default(false);
            $table->boolean('include_bpjs_tk_wage_base')->default(false);
            $table->boolean('include_thr_calculation_base')->default(false);
            $table->boolean('include_pph21_ter_gross')->default(false);
            $table->boolean('include_pph21_annual_reconciliation')->default(false);
            $table->boolean('subject_overtime_regulation')->default(false);
            $table->boolean('affects_net_pay')->default(true);
            $table->boolean('employer_cost_line')->default(false);
            $table->boolean('is_system_locked')->default(false);
            $table->unsignedSmallInteger('sort_order')->default(0);
            $table->boolean('is_active')->default(true);
            $table->timestamps();
        });

        $now = now();

        $rows = [
            [
                'code' => 'upah_pokok',
                'name' => 'Upah / Gaji Pokok',
                'description' => 'Komponen upah pokok sesuai perjanjian kerja.',
                'kind' => 'addition',
                'category' => 'basic_wage',
                'legal_basis' => 'UU No. 13 Tahun 2003 tentang Ketenagakerjaan (sebagaimana diubah) — pengertian upah.',
                'legal_notes' => 'Dasar utama penghitungan lembur (pembagi jam kerja), THR (pokok + tunjangan tetap), dan sering menjadi acuan iuran BPJS/PPh.',
                'include_bpjs_health_wage_base' => true,
                'include_bpjs_tk_wage_base' => true,
                'include_thr_calculation_base' => true,
                'include_pph21_ter_gross' => true,
                'include_pph21_annual_reconciliation' => true,
                'subject_overtime_regulation' => false,
                'affects_net_pay' => true,
                'employer_cost_line' => false,
                'sort_order' => 10,
            ],
            [
                'code' => 'tunjangan_tetap_transport',
                'name' => 'Tunjangan Tetap — Transport',
                'description' => 'Contoh tunjangan tetap; duplikasi/ubah nama sesuai kebijakan perusahaan.',
                'kind' => 'addition',
                'category' => 'fixed_allowance',
                'legal_basis' => 'Permenaker terkait THR — THR memasukkan upah pokok dan tunjangan tetap; UU Ketenagakerjaan tentang komponen upah.',
                'legal_notes' => 'Tunjangan tetap umumnya masuk basis THR dan dapat mempengaruhi gross untuk PPh 21 serta batas upah BPJS sesuai kebijakan internal & aturan terkini.',
                'include_bpjs_health_wage_base' => true,
                'include_bpjs_tk_wage_base' => true,
                'include_thr_calculation_base' => true,
                'include_pph21_ter_gross' => true,
                'include_pph21_annual_reconciliation' => true,
                'subject_overtime_regulation' => false,
                'affects_net_pay' => true,
                'employer_cost_line' => false,
                'sort_order' => 20,
            ],
            [
                'code' => 'tunjangan_tetap_jabatan',
                'name' => 'Tunjangan Tetap — Jabatan',
                'description' => 'Tunjangan tetap melekat pada jabatan.',
                'kind' => 'addition',
                'category' => 'fixed_allowance',
                'legal_basis' => 'UU Ketenagakerjaan & praktik THR (tunjangan tetap).',
                'legal_notes' => null,
                'include_bpjs_health_wage_base' => true,
                'include_bpjs_tk_wage_base' => true,
                'include_thr_calculation_base' => true,
                'include_pph21_ter_gross' => true,
                'include_pph21_annual_reconciliation' => true,
                'subject_overtime_regulation' => false,
                'affects_net_pay' => true,
                'employer_cost_line' => false,
                'sort_order' => 30,
            ],
            [
                'code' => 'uang_makan_tetap',
                'name' => 'Uang Makan Tetap',
                'description' => 'Tunjangan makan bersifat tetap (bukan reimbursement harian).',
                'kind' => 'addition',
                'category' => 'fixed_allowance',
                'legal_basis' => 'Klasifikasi sebagai tunjangan tetap mengikuti kebijakan perusahaan dan interpretasi pajak/JS.',
                'legal_notes' => 'Pastikan konsistensi dengan pembagian tetap vs tidak tetap untuk THR dan PPh.',
                'include_bpjs_health_wage_base' => true,
                'include_bpjs_tk_wage_base' => true,
                'include_thr_calculation_base' => true,
                'include_pph21_ter_gross' => true,
                'include_pph21_annual_reconciliation' => true,
                'subject_overtime_regulation' => false,
                'affects_net_pay' => true,
                'employer_cost_line' => false,
                'sort_order' => 40,
            ],
            [
                'code' => 'tunjangan_tidak_tetap',
                'name' => 'Tunjangan / Insentif Tidak Tetap',
                'description' => 'Komponen yang tidak bersifat tetap bulan ke bulan.',
                'kind' => 'addition',
                'category' => 'irregular_allowance',
                'legal_basis' => 'UU Ketenagakerjaan — pemisahan upah tetap dan tidak tetap; Permenaker THR (biasanya tidak masuk basis THR).',
                'legal_notes' => 'Verifikasi dengan aturan THR dan pajak untuk klasifikasi per komponen.',
                'include_bpjs_health_wage_base' => false,
                'include_bpjs_tk_wage_base' => false,
                'include_thr_calculation_base' => false,
                'include_pph21_ter_gross' => true,
                'include_pph21_annual_reconciliation' => true,
                'subject_overtime_regulation' => false,
                'affects_net_pay' => true,
                'employer_cost_line' => false,
                'sort_order' => 50,
            ],
            [
                'code' => 'upah_lembur',
                'name' => 'Upah Kerja Lembur',
                'description' => 'Kompensasi jam kerja melebihi ketentuan (termasuk referensi 1/173 untuk upah bulanan).',
                'kind' => 'addition',
                'category' => 'overtime',
                'legal_basis' => 'UU Ketenagakerjaan & PP Pengganti UU terkait waktu kerja dan upah lembur.',
                'legal_notes' => 'Tarif lembur (mis. 1.5x, 2x) dan dasar perhitungan mengikuti kontrak/ketentuan yang berlaku.',
                'include_bpjs_health_wage_base' => false,
                'include_bpjs_tk_wage_base' => false,
                'include_thr_calculation_base' => false,
                'include_pph21_ter_gross' => true,
                'include_pph21_annual_reconciliation' => true,
                'subject_overtime_regulation' => true,
                'affects_net_pay' => true,
                'employer_cost_line' => false,
                'sort_order' => 60,
            ],
            [
                'code' => 'thr',
                'name' => 'Tunjangan Hari Raya (THR)',
                'description' => 'THR sesuai ketentuan waktu dan besaran.',
                'kind' => 'addition',
                'category' => 'thr',
                'legal_basis' => 'Peraturan Menteri Ketenagakerjaan tentang THR bagi pekerja.',
                'legal_notes' => 'Basis THR umumnya upah pokok + tunjangan tetap; bukan komponen THR itu sendiri.',
                'include_bpjs_health_wage_base' => false,
                'include_bpjs_tk_wage_base' => false,
                'include_thr_calculation_base' => false,
                'include_pph21_ter_gross' => true,
                'include_pph21_annual_reconciliation' => true,
                'subject_overtime_regulation' => false,
                'affects_net_pay' => true,
                'employer_cost_line' => false,
                'sort_order' => 70,
            ],
            [
                'code' => 'bonus',
                'name' => 'Bonus (di luar THR)',
                'description' => 'Bonus produktivitas, kinerja, atau tahunan selain THR.',
                'kind' => 'addition',
                'category' => 'bonus',
                'legal_basis' => 'UU No. 7 Tahun 2021 (Harmonisasi Peraturan Perpajakan) — penghasilan dari pekerjaan.',
                'legal_notes' => 'Perlakuan pajak mengikuti ketentuan PPh 21 terkini (TER / rekonsiliasi).',
                'include_bpjs_health_wage_base' => false,
                'include_bpjs_tk_wage_base' => false,
                'include_thr_calculation_base' => false,
                'include_pph21_ter_gross' => true,
                'include_pph21_annual_reconciliation' => true,
                'subject_overtime_regulation' => false,
                'affects_net_pay' => true,
                'employer_cost_line' => false,
                'sort_order' => 80,
            ],
            [
                'code' => 'natura_kena_pajak',
                'name' => 'Natura & Kenikmatan Lain (kena pajak)',
                'description' => 'Natura yang merupakan objek PPh 21 sesuai ketentuan.',
                'kind' => 'addition',
                'category' => 'natura_taxable',
                'legal_basis' => 'UU PPh & peraturan pelaksana (PMK) tentang penghasilan tidak berwujud/natura.',
                'legal_notes' => 'Nilai yang diakui untuk pemotongan mengikuti aturan penilaian resmi.',
                'include_bpjs_health_wage_base' => false,
                'include_bpjs_tk_wage_base' => false,
                'include_thr_calculation_base' => false,
                'include_pph21_ter_gross' => true,
                'include_pph21_annual_reconciliation' => true,
                'subject_overtime_regulation' => false,
                'affects_net_pay' => true,
                'employer_cost_line' => false,
                'sort_order' => 90,
            ],
            [
                'code' => 'natura_tidak_kena_pajak',
                'name' => 'Natura (sesuai ketentuan tidak kena pajak)',
                'description' => 'Natura yang dikecualikan berdasarkan PMK/peraturan terkini.',
                'kind' => 'addition',
                'category' => 'natura_non_taxable',
                'legal_basis' => 'PMK terkait natura & kenikmatan tertentu yang tidak dipotong PPh.',
                'legal_notes' => 'Update manual jika ada perubahan daftar pengecualian.',
                'include_bpjs_health_wage_base' => false,
                'include_bpjs_tk_wage_base' => false,
                'include_thr_calculation_base' => false,
                'include_pph21_ter_gross' => false,
                'include_pph21_annual_reconciliation' => false,
                'subject_overtime_regulation' => false,
                'affects_net_pay' => true,
                'employer_cost_line' => false,
                'sort_order' => 100,
            ],
            [
                'code' => 'premi_jkk_pk',
                'name' => 'Premi JKK (beban perusahaan — informasi slip)',
                'description' => 'Iuran Jaminan Kecelakaan Kerja dibayar pemberi kerja; biasanya ditampilkan informatif.',
                'kind' => 'addition',
                'category' => 'employer_cost_display',
                'legal_basis' => 'UU No. 40 Tahun 2004 tentang Sistem Jaminan Sosial Nasional & program BPJS Ketenagakerjaan.',
                'legal_notes' => 'Besaran mengikuti kelas risiko dan tarif JKK; tidak mengurangi THP pekerja.',
                'include_bpjs_health_wage_base' => false,
                'include_bpjs_tk_wage_base' => false,
                'include_thr_calculation_base' => false,
                'include_pph21_ter_gross' => false,
                'include_pph21_annual_reconciliation' => false,
                'subject_overtime_regulation' => false,
                'affects_net_pay' => false,
                'employer_cost_line' => true,
                'sort_order' => 200,
            ],
            [
                'code' => 'premi_jkm_pk',
                'name' => 'Premi JKM (beban perusahaan — informasi slip)',
                'description' => 'Iuran Jaminan Kematian pemberi kerja.',
                'kind' => 'addition',
                'category' => 'employer_cost_display',
                'legal_basis' => 'UU Jamsostek/BPJS Ketenagakerjaan.',
                'legal_notes' => null,
                'include_bpjs_health_wage_base' => false,
                'include_bpjs_tk_wage_base' => false,
                'include_thr_calculation_base' => false,
                'include_pph21_ter_gross' => false,
                'include_pph21_annual_reconciliation' => false,
                'subject_overtime_regulation' => false,
                'affects_net_pay' => false,
                'employer_cost_line' => true,
                'sort_order' => 210,
            ],
            [
                'code' => 'iuran_jht_pk',
                'name' => 'Iuran JHT pihak perusahaan (informasi slip)',
                'description' => 'Kontribusi JHT pemberi kerja sesuai tarif berlaku.',
                'kind' => 'addition',
                'category' => 'employer_cost_display',
                'legal_basis' => 'Program BPJS Ketenagakerjaan.',
                'legal_notes' => null,
                'include_bpjs_health_wage_base' => false,
                'include_bpjs_tk_wage_base' => false,
                'include_thr_calculation_base' => false,
                'include_pph21_ter_gross' => false,
                'include_pph21_annual_reconciliation' => false,
                'subject_overtime_regulation' => false,
                'affects_net_pay' => false,
                'employer_cost_line' => true,
                'sort_order' => 220,
            ],
            [
                'code' => 'iuran_jp_pk',
                'name' => 'Iuran JP pihak perusahaan (informasi slip)',
                'description' => 'Kontribusi Jaminan Pensiun pemberi kerja.',
                'kind' => 'addition',
                'category' => 'employer_cost_display',
                'legal_basis' => 'Program BPJS Ketenagakerjaan.',
                'legal_notes' => null,
                'include_bpjs_health_wage_base' => false,
                'include_bpjs_tk_wage_base' => false,
                'include_thr_calculation_base' => false,
                'include_pph21_ter_gross' => false,
                'include_pph21_annual_reconciliation' => false,
                'subject_overtime_regulation' => false,
                'affects_net_pay' => false,
                'employer_cost_line' => true,
                'sort_order' => 230,
            ],
            [
                'code' => 'iuran_bpjs_kes_pk',
                'name' => 'Iuran BPJS Kesehatan pihak perusahaan (informasi slip)',
                'description' => 'Kontribusi non-pekerja pada JKN-KIS sesuai tarif.',
                'kind' => 'addition',
                'category' => 'employer_cost_display',
                'legal_basis' => 'UU Jamsostek & Perpres terkait BPJS Kesehatan.',
                'legal_notes' => null,
                'include_bpjs_health_wage_base' => false,
                'include_bpjs_tk_wage_base' => false,
                'include_thr_calculation_base' => false,
                'include_pph21_ter_gross' => false,
                'include_pph21_annual_reconciliation' => false,
                'subject_overtime_regulation' => false,
                'affects_net_pay' => false,
                'employer_cost_line' => true,
                'sort_order' => 240,
            ],
            [
                'code' => 'iuran_bpjs_kes_pekerja',
                'name' => 'Iuran BPJS Kesehatan (peserta pekerja)',
                'description' => 'Potongan iuran JKN-KIS bagian pekerja.',
                'kind' => 'deduction',
                'category' => 'bpjs_health_employee',
                'legal_basis' => 'UU No. 40 Tahun 2004 & tarif iuran BPJS Kesehatan.',
                'legal_notes' => 'Tarif dan batas upah mengikuti aturan yang berlaku.',
                'include_bpjs_health_wage_base' => false,
                'include_bpjs_tk_wage_base' => false,
                'include_thr_calculation_base' => false,
                'include_pph21_ter_gross' => false,
                'include_pph21_annual_reconciliation' => false,
                'subject_overtime_regulation' => false,
                'affects_net_pay' => true,
                'employer_cost_line' => false,
                'sort_order' => 300,
            ],
            [
                'code' => 'iuran_jht_pekerja',
                'name' => 'Iuran JHT (pekerja)',
                'description' => 'Potongan Jaminan Hari Tua bagian pekerja.',
                'kind' => 'deduction',
                'category' => 'bpjs_jht_employee',
                'legal_basis' => 'Program BPJS Ketenagakerjaan.',
                'legal_notes' => null,
                'include_bpjs_health_wage_base' => false,
                'include_bpjs_tk_wage_base' => false,
                'include_thr_calculation_base' => false,
                'include_pph21_ter_gross' => false,
                'include_pph21_annual_reconciliation' => false,
                'subject_overtime_regulation' => false,
                'affects_net_pay' => true,
                'employer_cost_line' => false,
                'sort_order' => 310,
            ],
            [
                'code' => 'iuran_jp_pekerja',
                'name' => 'Iuran JP / Jaminan Pensiun (pekerja)',
                'description' => 'Potongan JP sesuai program yang diikuti.',
                'kind' => 'deduction',
                'category' => 'bpjs_jp_employee',
                'legal_basis' => 'Program BPJS Ketenagakerjaan.',
                'legal_notes' => null,
                'include_bpjs_health_wage_base' => false,
                'include_bpjs_tk_wage_base' => false,
                'include_thr_calculation_base' => false,
                'include_pph21_ter_gross' => false,
                'include_pph21_annual_reconciliation' => false,
                'subject_overtime_regulation' => false,
                'affects_net_pay' => true,
                'employer_cost_line' => false,
                'sort_order' => 320,
            ],
            [
                'code' => 'pph21_ter',
                'name' => 'PPh Pasal 21 — pemotongan TER (bulanan)',
                'description' => 'Pemotongan pajak penghasilan dengan tarif efektif / TER sesuai regulasi terkini.',
                'kind' => 'deduction',
                'category' => 'pph21_ter',
                'legal_basis' => 'UU No. 7 Tahun 2021; PMK 168/PMK.03/2023; PP 58 Tahun 2023 tentang tarif pemotongan PPh 21.',
                'legal_notes' => 'Kategori TER (A/B/C) dan penyesuaian tahunan mengikuti petunjuk DJP.',
                'include_bpjs_health_wage_base' => false,
                'include_bpjs_tk_wage_base' => false,
                'include_thr_calculation_base' => false,
                'include_pph21_ter_gross' => false,
                'include_pph21_annual_reconciliation' => true,
                'subject_overtime_regulation' => false,
                'affects_net_pay' => true,
                'employer_cost_line' => false,
                'sort_order' => 330,
            ],
            [
                'code' => 'pph21_rekonsiliasi',
                'name' => 'PPh 21 — penyesuaian / rekonsiliasi (mis. Desember)',
                'description' => 'Selisih pajak akhir tahun atau penyesuaian sesuai perhitungan sebenarnya.',
                'kind' => 'deduction',
                'category' => 'pph21_december_recon',
                'legal_basis' => 'Ketentuan PPh 21 untuk penyesuaian di akhir tahun pajak pekerja.',
                'legal_notes' => 'Nilai bisa positif (kurang potong) atau negatif tergantung implementasi slip; gunakan komponen terpisah jika perlu.',
                'include_bpjs_health_wage_base' => false,
                'include_bpjs_tk_wage_base' => false,
                'include_thr_calculation_base' => false,
                'include_pph21_ter_gross' => false,
                'include_pph21_annual_reconciliation' => true,
                'subject_overtime_regulation' => false,
                'affects_net_pay' => true,
                'employer_cost_line' => false,
                'sort_order' => 340,
            ],
            [
                'code' => 'potongan_koperasi',
                'name' => 'Potongan koperasi / internal',
                'description' => 'Potongan selain wajib negara (mis. simpanan wajib koperasi).',
                'kind' => 'deduction',
                'category' => 'internal_cooperative',
                'legal_basis' => 'Perjanjian kerja / peraturan perusahaan & persetujuan pekerja.',
                'legal_notes' => 'Bukan kewajiban perpajakan; pastikan dokumen pendukung.',
                'include_bpjs_health_wage_base' => false,
                'include_bpjs_tk_wage_base' => false,
                'include_thr_calculation_base' => false,
                'include_pph21_ter_gross' => false,
                'include_pph21_annual_reconciliation' => false,
                'subject_overtime_regulation' => false,
                'affects_net_pay' => true,
                'employer_cost_line' => false,
                'sort_order' => 400,
            ],
            [
                'code' => 'potongan_pinjaman',
                'name' => 'Potongan pinjaman karyawan',
                'description' => 'Cicilan pinjaman ke perusahaan.',
                'kind' => 'deduction',
                'category' => 'internal_loan',
                'legal_basis' => 'Perjanjian pinjaman antara pekerja dan perusahaan.',
                'legal_notes' => null,
                'include_bpjs_health_wage_base' => false,
                'include_bpjs_tk_wage_base' => false,
                'include_thr_calculation_base' => false,
                'include_pph21_ter_gross' => false,
                'include_pph21_annual_reconciliation' => false,
                'subject_overtime_regulation' => false,
                'affects_net_pay' => true,
                'employer_cost_line' => false,
                'sort_order' => 410,
            ],
        ];

        foreach ($rows as $row) {
            DB::table('hcm_salary_components')->insert(array_merge($row, [
                'is_system_locked' => true,
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ]));
        }
    }

    public function down(): void
    {
        Schema::dropIfExists('hcm_salary_components');
    }
};
