<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        $now = now();

        $rows = [
            [
                'code' => 'tunjangan_komunikasi_tetap',
                'name' => 'Tunjangan Tetap — Komunikasi',
                'description' => 'Tunjangan komunikasi bulanan yang dibayarkan tetap.',
                'kind' => 'addition',
                'category' => 'fixed_allowance',
                'legal_basis' => 'Kebijakan perusahaan / perjanjian kerja.',
                'legal_notes' => 'Jika bersifat tetap, umumnya diperlakukan sebagai tunjangan tetap.',
                'include_bpjs_health_wage_base' => true,
                'include_bpjs_tk_wage_base' => true,
                'include_thr_calculation_base' => true,
                'include_pph21_ter_gross' => true,
                'include_pph21_annual_reconciliation' => true,
                'subject_overtime_regulation' => false,
                'affects_net_pay' => true,
                'employer_cost_line' => false,
                'is_system_locked' => false,
                'sort_order' => 45,
                'is_active' => true,
            ],
            [
                'code' => 'tunjangan_shift',
                'name' => 'Tunjangan Shift',
                'description' => 'Tunjangan untuk pola kerja shift.',
                'kind' => 'addition',
                'category' => 'irregular_allowance',
                'legal_basis' => 'Kebijakan perusahaan / aturan kerja shift.',
                'legal_notes' => 'Biasanya tidak menjadi basis THR bila tidak tetap.',
                'include_bpjs_health_wage_base' => false,
                'include_bpjs_tk_wage_base' => false,
                'include_thr_calculation_base' => false,
                'include_pph21_ter_gross' => true,
                'include_pph21_annual_reconciliation' => true,
                'subject_overtime_regulation' => false,
                'affects_net_pay' => true,
                'employer_cost_line' => false,
                'is_system_locked' => false,
                'sort_order' => 55,
                'is_active' => true,
            ],
            [
                'code' => 'insentif_kehadiran',
                'name' => 'Insentif Kehadiran',
                'description' => 'Insentif berdasarkan pencapaian kehadiran.',
                'kind' => 'addition',
                'category' => 'irregular_allowance',
                'legal_basis' => 'Kebijakan internal absensi dan insentif.',
                'legal_notes' => null,
                'include_bpjs_health_wage_base' => false,
                'include_bpjs_tk_wage_base' => false,
                'include_thr_calculation_base' => false,
                'include_pph21_ter_gross' => true,
                'include_pph21_annual_reconciliation' => true,
                'subject_overtime_regulation' => false,
                'affects_net_pay' => true,
                'employer_cost_line' => false,
                'is_system_locked' => false,
                'sort_order' => 56,
                'is_active' => true,
            ],
            [
                'code' => 'komisi_penjualan',
                'name' => 'Komisi Penjualan',
                'description' => 'Komisi berdasarkan pencapaian penjualan.',
                'kind' => 'addition',
                'category' => 'bonus',
                'legal_basis' => 'Skema komisi sesuai perjanjian kerja / kebijakan sales.',
                'legal_notes' => null,
                'include_bpjs_health_wage_base' => false,
                'include_bpjs_tk_wage_base' => false,
                'include_thr_calculation_base' => false,
                'include_pph21_ter_gross' => true,
                'include_pph21_annual_reconciliation' => true,
                'subject_overtime_regulation' => false,
                'affects_net_pay' => true,
                'employer_cost_line' => false,
                'is_system_locked' => false,
                'sort_order' => 85,
                'is_active' => true,
            ],
            [
                'code' => 'rapel_gaji',
                'name' => 'Rapel Gaji / Penyesuaian Upah',
                'description' => 'Pembayaran rapel atas koreksi periode sebelumnya.',
                'kind' => 'addition',
                'category' => 'other_addition',
                'legal_basis' => 'Koreksi penggajian internal.',
                'legal_notes' => 'Gunakan dengan catatan periode referensi rapel.',
                'include_bpjs_health_wage_base' => false,
                'include_bpjs_tk_wage_base' => false,
                'include_thr_calculation_base' => false,
                'include_pph21_ter_gross' => true,
                'include_pph21_annual_reconciliation' => true,
                'subject_overtime_regulation' => false,
                'affects_net_pay' => true,
                'employer_cost_line' => false,
                'is_system_locked' => false,
                'sort_order' => 110,
                'is_active' => true,
            ],
            [
                'code' => 'koreksi_penghasilan',
                'name' => 'Koreksi Penghasilan Lain',
                'description' => 'Penyesuaian tambahan penghasilan selain rapel.',
                'kind' => 'addition',
                'category' => 'other_addition',
                'legal_basis' => 'Koreksi internal payroll.',
                'legal_notes' => null,
                'include_bpjs_health_wage_base' => false,
                'include_bpjs_tk_wage_base' => false,
                'include_thr_calculation_base' => false,
                'include_pph21_ter_gross' => true,
                'include_pph21_annual_reconciliation' => true,
                'subject_overtime_regulation' => false,
                'affects_net_pay' => true,
                'employer_cost_line' => false,
                'is_system_locked' => false,
                'sort_order' => 111,
                'is_active' => true,
            ],
            [
                'code' => 'potongan_absensi',
                'name' => 'Potongan Absensi',
                'description' => 'Potongan karena ketidakhadiran sesuai kebijakan.',
                'kind' => 'deduction',
                'category' => 'other_statutory',
                'legal_basis' => 'Peraturan perusahaan / perjanjian kerja.',
                'legal_notes' => null,
                'include_bpjs_health_wage_base' => false,
                'include_bpjs_tk_wage_base' => false,
                'include_thr_calculation_base' => false,
                'include_pph21_ter_gross' => false,
                'include_pph21_annual_reconciliation' => false,
                'subject_overtime_regulation' => false,
                'affects_net_pay' => true,
                'employer_cost_line' => false,
                'is_system_locked' => false,
                'sort_order' => 350,
                'is_active' => true,
            ],
            [
                'code' => 'potongan_keterlambatan',
                'name' => 'Potongan Keterlambatan',
                'description' => 'Potongan keterlambatan sesuai ketentuan internal.',
                'kind' => 'deduction',
                'category' => 'other_deduction',
                'legal_basis' => 'Kebijakan disiplin kerja perusahaan.',
                'legal_notes' => null,
                'include_bpjs_health_wage_base' => false,
                'include_bpjs_tk_wage_base' => false,
                'include_thr_calculation_base' => false,
                'include_pph21_ter_gross' => false,
                'include_pph21_annual_reconciliation' => false,
                'subject_overtime_regulation' => false,
                'affects_net_pay' => true,
                'employer_cost_line' => false,
                'is_system_locked' => false,
                'sort_order' => 420,
                'is_active' => true,
            ],
            [
                'code' => 'potongan_serikat_karyawan',
                'name' => 'Potongan Iuran Serikat Karyawan',
                'description' => 'Potongan iuran keanggotaan serikat karyawan (jika ada).',
                'kind' => 'deduction',
                'category' => 'internal_other',
                'legal_basis' => 'Persetujuan pekerja dan ketentuan serikat.',
                'legal_notes' => null,
                'include_bpjs_health_wage_base' => false,
                'include_bpjs_tk_wage_base' => false,
                'include_thr_calculation_base' => false,
                'include_pph21_ter_gross' => false,
                'include_pph21_annual_reconciliation' => false,
                'subject_overtime_regulation' => false,
                'affects_net_pay' => true,
                'employer_cost_line' => false,
                'is_system_locked' => false,
                'sort_order' => 430,
                'is_active' => true,
            ],
            [
                'code' => 'denda_internal',
                'name' => 'Denda Internal',
                'description' => 'Denda administratif internal sesuai aturan perusahaan.',
                'kind' => 'deduction',
                'category' => 'internal_other',
                'legal_basis' => 'Peraturan perusahaan yang disepakati.',
                'legal_notes' => 'Gunakan sesuai compliance ketenagakerjaan yang berlaku.',
                'include_bpjs_health_wage_base' => false,
                'include_bpjs_tk_wage_base' => false,
                'include_thr_calculation_base' => false,
                'include_pph21_ter_gross' => false,
                'include_pph21_annual_reconciliation' => false,
                'subject_overtime_regulation' => false,
                'affects_net_pay' => true,
                'employer_cost_line' => false,
                'is_system_locked' => false,
                'sort_order' => 440,
                'is_active' => true,
            ],
            [
                'code' => 'koreksi_potongan',
                'name' => 'Koreksi Potongan',
                'description' => 'Penyesuaian potongan karena koreksi periode sebelumnya.',
                'kind' => 'deduction',
                'category' => 'other_deduction',
                'legal_basis' => 'Koreksi internal payroll.',
                'legal_notes' => null,
                'include_bpjs_health_wage_base' => false,
                'include_bpjs_tk_wage_base' => false,
                'include_thr_calculation_base' => false,
                'include_pph21_ter_gross' => false,
                'include_pph21_annual_reconciliation' => false,
                'subject_overtime_regulation' => false,
                'affects_net_pay' => true,
                'employer_cost_line' => false,
                'is_system_locked' => false,
                'sort_order' => 450,
                'is_active' => true,
            ],
        ];

        foreach ($rows as $row) {
            $exists = DB::table('hcm_salary_components')->where('code', $row['code'])->exists();
            if ($exists) {
                DB::table('hcm_salary_components')
                    ->where('code', $row['code'])
                    ->update(array_merge($row, ['updated_at' => $now]));
                continue;
            }

            DB::table('hcm_salary_components')->insert(array_merge($row, [
                'created_at' => $now,
                'updated_at' => $now,
            ]));
        }
    }

    public function down(): void
    {
        DB::table('hcm_salary_components')->whereIn('code', [
            'tunjangan_komunikasi_tetap',
            'tunjangan_shift',
            'insentif_kehadiran',
            'komisi_penjualan',
            'rapel_gaji',
            'koreksi_penghasilan',
            'potongan_absensi',
            'potongan_keterlambatan',
            'potongan_serikat_karyawan',
            'denda_internal',
            'koreksi_potongan',
        ])->delete();
    }
};
